### ISSUE TITLE
ValueError: Error while parsing pdf_file.pdf: This event loop is already running

### ISSUE THREAD

**Issue by akshaytheau** [QuivrHQ/MegaParse#200]
Details :

megaparser version = 0.0.48
python version = 3.11.5
IDE = VS code ipynb

Getting this error while running below code

from megaparse import MegaParse
from langchain_openai import ChatOpenAI
from megaparse.parser.unstructured_parser import UnstructuredParser

parser = UnstructuredParser()
megaparse = MegaParse(parser)
response = megaparse.load("./india.pdf")
print(response)
megaparse.save("./india.md")

**Comment by gemini-mouse** [comment]
same issue, already changed to python 3.11, but doesn't work

**Comment by jayesh-caapl** [comment]
same issue

**Comment by akshaytheau** [comment]
Can you please let me know the release planning date.

**Comment by rdewolff** [comment]
I have encountered the same issue. 

Any update on the release containing this fix?
