### ISSUE TITLE
I found a bug: using llama_parse can only parse one page of pdf files.I givemy solution

### ISSUE THREAD

**Issue by star-rui** [QuivrHQ/MegaParse#60]
MegaParse/megaparse
Line 276 of code in /Converter.py should be changed to:

```
parsed_md = ""
for document in documents:
     text_content = document.text
parsed_md = parsed_md + text_content
```

If we do not modify the code, the use of llama_parse can only parse a page pdf file

**Comment by chloedia** [comment]
Thanks for mentioning the issue, problem fixed ! :)
